version: '3'
services:    
    # Nginx Service
    app:
        image: nginx:alpine        
        restart: unless-stopped
        tty: true
        ports:
        - "80:80"
        volumes:
        - ../:/var/www
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-net

    php:
        container_name: instorex_php
        build:
            context: ./
            dockerfile: php/DockerFile
        volumes:
            - ../:/var/www        
        links:
            - mysql
        networks:
            -  app-net

    mysql:
        container_name: instorex_mysql
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: instorex
            MYSQL_USER: instorex
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root                                
        networks:
            -  app-net
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

networks:
     app-net:
        driver: bridge
